# Generated by Django 3.0.5 on 2020-04-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200429_1852'),
        ('menus', '0002_auto_20200429_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dishes', to='users.Company'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menus', to='users.Company'),
        ),
    ]
